# Generated by Django 3.1.12 on 2025-01-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0002_auto_20250102_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetail',
            name='empId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
